class CreateFaafacilities < ActiveRecord::Migration
  def change
    create_table :faafacilities do |t|
      t.string :SiteNumber
      t.string :Type
	t.string :LocationID
      t.string :EffectiveDate
      t.string :Region
      t.string :DistrictOffice
      t.string :State
      t.string :StateName
      t.string :County
      t.string :CountyState
      t.string :City
      t.string :FacilityName
      t.string :Ownership
      t.string :Use
      t.string :Owner
      t.string :OwnerAddress
      t.string :OwnerCSZ
      t.string :OwnerPhone
      t.string :Manager
      t.string :ManagerAddress
      t.string :ManagerCSZ
      t.string :ManagerPhone
      t.string :ARPLatitude
      t.string :ARPLatitudeS
      t.string :ARPLongitude
      t.string :ARPLongitudeS
      t.string :ARPMethod
      t.string :ARPElevation
      t.string :ARPElevationMethod
      t.string :MagneticVariation
      t.string :MagneticVariationYear
      t.string :TrafficPatternAltitude
      t.string :ChartName
      t.string :DistanceFromCBD
      t.string :DirectionFromCBD
      t.string :LandAreaCoveredByAirport
      t.string :BoundaryARTCCID
      t.string :BoundaryARTCCComputerID
      t.string :BoundaryARTCCName
      t.string :ResponsibleARTCCID
      t.string :ResponsibleARTCCComputerID
      t.string :ResponsibleARTCCName
      t.string :TieInFSS
      t.string :TieInFSSID
      t.string :TieInFSSName
      t.string :AirportToFSSPhoneNumber
      t.string :TieInFSSTollFreeNumber
      t.string :AlternateFSSID
      t.string :AlternateFSSName
      t.string :AlternateFSSTollFreeNumber
      t.string :NOTAMFacilityID
      t.string :NOTAMService
      t.string :ActiviationDate
      t.string :AirportStatusCode
      t.string :CertificationTypeDate
      t.string :FederalAgreements
      t.string :AirspaceDetermination
      t.string :CustomsAirportOfEntry
      t.string :CustomsLandingRights
      t.string :MilitaryJointUse
      t.string :MilitaryLandingRights
      t.string :InspectionMethod
      t.string :InspectionGroup
      t.string :LastInspectionDate
      t.string :LastOwnerInformationDate
      t.string :FuelTypes
      t.string :AirframeRepair
      t.string :PowerPlantRepair
      t.string :BottledOxygenType
      t.string :BulkOxygenType
      t.string :LightingSchedule
      t.string :BeaconSchedule
      t.string :ATCT
      t.string :UNICOMFrequencies
      t.string :CTAFFrequency
      t.string :SegmentedCircle
      t.string :BeaconColor
      t.string :NonCommercialLandingFee
      t.string :MedicalUse
      t.string :SingleEngineGA
      t.string :MultiEngineGA
      t.string :JetEngineGA
      t.string :HelicoptersGA
      t.string :GlidersOperational
      t.string :MilitaryOperational
      t.string :Ultralights
      t.string :OperationsCommercial
      t.string :OperationsCommuter
      t.string :OperationsAirTaxi
      t.string :OperationsGALocal
      t.string :OperationsGAItin
      t.string :OperationsMilitary
      t.string :OperationsDate
      t.string :AirportPositionSource
      t.string :AirportPositionSourceDate
      t.string :AirportElevationSource
      t.string :AirportElevationSourceDate
      t.string :ContractFuelAvailable
      t.string :TransientStorage
      t.string :OtherServices
      t.string :WindIndicator

      t.timestamps
    end
  end
end
