class CreateFaarunways < ActiveRecord::Migration
  def change
    create_table :faarunways do |t|
	t.string :RunwayID
	t.string :RunwayLength
	t.string :RunwayWidth
	t.string :RunwaySurfaceTypeCondition
	t.string :RunwaySurfaceTreatment
	t.string :PavementClass
	t.string :RunwayWeightBearingCapacitySW
	t.string :RunwayWeightBearingCapacityDW
	t.string :RunwayWeightBearingCapacityDT
	t.string :RunwayWeightBearingCapacityDDT
	t.string :EdgeLightsIntensity
	t.string :BaseEndID
	t.string :BaseEndTrueAlignment
	t.string :BaseEndILSType
	t.string :BaseEndRightTrafficPattern
	t.string :BaseEndMarkingsType
	t.string :BaseEndMarkingsCondition
	t.string :BaseEndPhysicalLatitude
	t.string :BaseEndPhysicalLatitudeS
	t.string :BaseEndPhysicalLongitude
	t.string :BaseEndPhysicalLongitudeS
	t.string :BaseEndPhysicalElevation
	t.string :BaseEndCrossingHeight
	t.string :BaseEndGlidePathAngle
	t.string :BaseEndDisplacedLatitude
	t.string :BaseEndDisplacedLatitudeS
	t.string :BaseEndDisplacedLongitude
	t.string :BaseEndDisplacedLongitudeS
	t.string :BaseEndDisplacedElevation
	t.string :BaseEndDisplacedLength
	t.string :BaseEndTDZElevation
	t.string :BaseEndVASI
	t.string :BaseEndRVR
	t.string :BaseEndRVV
	t.string :BaseEndALS
	t.string :BaseEndREIL
	t.string :BaseEndCenterlineLights
	t.string :BaseEndTouchdownLights
	t.string :BaseEndObjectDescription
	t.string :BaseEndObjectMarkLight
	t.string :BaseEndPart77Category
	t.string :BaseEndObjectClearSlope
	t.string :BaseEndObjectHeight
	t.string :BaseEndObjectDistance
	t.string :BaseEndObjectOffset
	t.string :ReciprocalEndID
	t.string :ReciprocalEndTrueAlignment
	t.string :ReciprocalEndILSType
	t.string :ReciprocalEndRightTrafficPattern
	t.string :ReciprocalEndMarkingsType
	t.string :ReciprocalEndMarkingsCondition
	t.string :ReciprocalEndPhysicalLatitude
	t.string :ReciprocalEndPhysicalLatitudeS
	t.string :ReciprocalEndPhysicalLongitude
	t.string :ReciprocalEndPhysicalLongitudeS
	t.string :ReciprocalEndPhysicalElevation
	t.string :ReciprocalEndCrossingHeight
	t.string :ReciprocalEndGlidePathAngle
	t.string :ReciprocalEndDisplacedLatitude
	t.string :ReciprocalEndDisplacedLatitudeS
	t.string :ReciprocalEndDisplacedLongitude
	t.string :ReciprocalEndDisplacedLongitudeS
	t.string :ReciprocalEndDisplacedElevation
	t.string :ReciprocalEndDisplacedLength
	t.string :ReciprocalEndTDZElevation
	t.string :ReciprocalEndVASI
	t.string :ReciprocalEndRVR
	t.string :ReciprocalEndRVV
	t.string :ReciprocalEndALS
	t.string :ReciprocalEndREIL
	t.string :ReciprocalEndCenterlineLights
	t.string :ReciprocalEndTouchdownLights
	t.string :ReciprocalEndObjectDescription
	t.string :ReciprocalEndObjectMarkLight
	t.string :ReciprocalEndPart77Category
	t.string :ReciprocalEndObjectClearSlope
	t.string :ReciprocalEndObjectHeight
	t.string :ReciprocalEndObjectDistance
	t.string :ReciprocalEndObjectOffset
	t.string :RunwayLengthSource
	t.string :RunwayLengthSourceDate
	t.string :BaseEndGradient
	t.string :BaseEndGradientDirection
	t.string :BaseEndPositionSource
	t.string :BaseEndPositionSourceDate
	t.string :BaseEndElevationSource
	t.string :BaseEndElevationSourceDate
	t.string :BaseEndDisplacedThresholdPositionSource
	t.string :BaseEndDisplacedThresholdPositionSourceDate
	t.string :BaseEndDisplacedThresholdElevationSource
	t.string :BaseEndDisplacedThresholdElevationSourceDate
	t.string :BaseEndTouchdownZoneElevationSource
	t.string :BaseEndTouchdownZoneElevationSourceDate
	t.string :BaseEndTakeOffRunAvailableTORA
	t.string :BaseEndTakeOffDistanceAvailableTODA
	t.string :BaseEndAcltStopDistanceAvailableASDA
	t.string :BaseEndLandingDistanceAvailableLDA
	t.string :ReciprocalEndGradient
	t.string :ReciprocalEndGradientDirection
	t.string :ReciprocalEndPositionSource
	t.string :ReciprocalEndPositionSourceDate
	t.string :ReciprocalEndElevationSource
	t.string :ReciprocalEndElevationSourceDate
	t.string :ReciprocalEndDisplacedThresholdPositionSource
	t.string :ReciprocalEndDisplacedThresholdPositionSourceDate
	t.string :ReciprocalEndDisplacedThresholdElevationSource
	t.string :ReciprocalEndDisplacedThresholdElevationSourceDate
	t.string :ReciprocalEndTouchdownZoneElevationSource
	t.string :ReciprocalEndTouchdownZoneElevationSourceDate
	t.string :ReciprocalEndTakeOffRunAvailableTORA
	t.string :ReciprocalEndTakeOffDistanceAvailableTODA
	t.string :ReciprocalEndAcltStopDistanceAvailableASDA
	t.string :ReciprocalEndLandingDistanceAvailableLDA
	t.integer :faafacility_id

    t.timestamps
    end
    add_index :faarunways, :faafacility_id
  end
end
